### PR TITLE
Add nodejs and upgrade ruby to 2.3.3

### PR DESCRIPTION
**Pull request by juanpedrojose**

### CODE REVIEW

**Comment by skovsgaard** [comment]
Are we replacing libv8 with Node or why is it needed here?

**Comment by juanpedrojose** [comment]
Yes, we are.
leadmanager and geo_manager are already using that.

**Comment by skovsgaard** [comment]
Perfect. So the only real change here is that we're applying it globally?

**Comment by juanpedrojose** [comment]
Yes, and it is available already at dockerhub under tag `2.3.3`

**Pull request merged**
